export const ORDEM_SERVICE = {
    id: "",
    
    OS_number: null,
    company: null,

    equipament: null,
  
    cga_reason_visit: null,
    cga_reported_defect: null,
    cga_solution_applied: null,
    cga_replaced_parts: null,
    cga_parts_to_replace: null,
  
    mp_oil: null,
    mp_air_oil_separator_element: null,
    mp_primary_air_filter: null,
    mp_secondary_air_filter: null,
    mp_standard_air_filter: null,
    mp_oil_filter: null,
    mp_engine_lubricant: null,
    mp_coalescing_element: null,
    mp_compressor_element_revision: null,
  
    rr_lubricating_oil_level: null,
    rr_oil_stock_quantity: null,
    rr_oil_model: null,
    rr_oil_type: null,
    rr_supply_voltage_under_load: null,
    rr_supply_voltage_unloaded: null,
    rr_service_factor_current: null,
    rr_electrical_current_under_load: null,
    rr_electrical_current_unloaded: null,
    rr_fan_motor_current: null,
    rr_compressor_operating_temperature: null,
    rr_dryer_current: null,
    rr_motor_lubrication_data: null,
    rr_dew_point_temperature: null,
    rr_ambient_temperature: null,
    rr_coalescing_filter_model: null,
  
    cr_hot_air_duct_ok: null,
    cr_hot_air_duct_regularized: null,
    cr_room_temp_vent_ok: null,
    cr_room_notes: null,
    cr_install_env_condition: null,
    cr_accident_risk: null,
    cr_electrical_install_ok: null,
    cr_grounding_ok: null,
    cr_room_lighting_ok: null,
    cr_service_outlet_220v: null,
    cr_air_point_for_cleaning: null,
    cr_water_point_available: null,
    cr_distancing_ok: null,
    cr_compressor_ok: null,
    cr_improvement_suggestions: null,
  
    closing_start_time: null,
    closing_end_time: null,
    closing_responsible: null,
    closing_technician_responsible: null,
    closing_notes: null,

    attachments: [],

    signature: null,
  };